### ISSUE TITLE
Feature request: touchpad toggle

### ISSUE THREAD

**Issue by barnscott** [shyzus/gnome-shell-extension-screen-autorotate#31]
**Is your feature request related to a problem? Please describe.**
Add option in settings-panel to disable the touchpad when screen rotates.

**Describe the solution you'd like**
Toggle added to settings panel called something similar to "Disable touchpad on screen rotation". When this setting is enabled, and the display is rotated, it will trigger the dconf parameter "org.gnome.desktop.peripherals.touchpad" property "send-events" from "enabled" to "disabled".

**Describe alternatives you've considered**
Other extensions?

**Additional context**

**Comment by shyzus** [comment]
@barnscott Thank you for creating this issue.

I am considering merging the issue #32 of @larmoe with this one. I believe the best resolution for both would be to add a set of toggles in the extension's preferences page for the user to select one or more orientations where if selected, the extension will disable the touchpad.

There is one problem that comes to mind with this approach. Which is if a user were to want to re-enable their touchpad but has selected all orientations in the extension's preferences to disable the touchpad. The user would have to use a external mouse or use the keyboard to open a terminal to enable the touchpad.

I believe the best way to handle this would be to by default prevent more than 3 out of 4 orientations to be selected but give the user a way to override this default while warning them about the above problem before applying the setting.

Opinions? @barnscott @larmoe

**Comment by barnscott** [comment]
I think your suggestion is satisfactory. Thank you!

I suspect that folks who desire to disable the touchpad typically have a touchscreen, and can still fallback to re-enable the touchpad with touch input. A warning pop-up presented for folks who don't fully appreciate what they are doing should be sufficient.

**Comment by larmoe** [comment]
@shyzus thanks for a swift reply. Laptops capable of flipping in to tablet configuration typical have a touch-screen, which enables the user to re-enable touchpad and keyboard on screen.
For those accidental disabling this feature in the absences of a touchscreen (and relying on auto-rotation), limiting this feature to 3 of 4 orientations would be a nice solution.

**Comment by larmoe** [comment]
... on second thought. Disabling touchpad and keyboard in all 4 orientations would be desirable.  A solution could look like:
1. An option in settings to enable the feature followed by a warning.
2. A button in the drop-down list to toggle touchpad and keyboard on/off

**Comment by shyzus** [comment]
Thank you for both of your feedback. I will be working on this and I will be closing #32 as it will be resolved via this issue as well.

I will reach out to both of you when testing of this feature is needed.

**Comment by shyzus** [comment]
I have some good news and bad news. :smiling_face_with_tear: 

I believe that the code in this [branch](https://github.com/shyzus/gnome-shell-extension-screen-autorotate/tree/31-feature-request-touchpad-keyboard-toggle) is ready to be tested. @barnscott @larmoe feel free to test it I look forward to your opinion. That is the good news.

The bad news is that it seems that only the touchpad part of this issue can be resolved in a good way. Disabling the keyboard is not as straight forward compared to the touchpad. This is mainly because there is no equivalent option to the 'send-events' exposed via Gsettings but for the keyboard. 

Other ways of disabling the keyboard either result in restricting all input including that of a screen keyboard, which makes that a no-go. Other alternatives is going the more hacky route like one [fork](https://github.com/lkwslr/gnome-shell-extension-convertible-helper/tree/main) has of this extension. While this does achieve the functionality desired. It does so at the cost of going against many E.G.O review guidelines which would make it unlikely for this change to be pushed to E.G.O.

Additionally it seems that the forks solution is unlikely to work universally as it relies on specific hardware path/id's and requires administrator privileges.

I believe the best way going forward is re-opening up @larmoe 's issue and to create an issue at the [gsettings-desktop-schemas](https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas) repo to add in a similar type of option as `send-events` but for the keyboard peripheral.

**Comment by pktiuk** [comment]
> and to create an issue at the [gsettings-desktop-schemas](https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas) repo to add in a similar type of option as send-events but for the keyboard peripheral.

@shyzus   
Is this issue already created? I was looking for it in that gnome's repo, but I found nothing.

**Comment by shyzus** [comment]
> > and to create an issue at the [gsettings-desktop-schemas](https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas) repo to add in a similar type of option as send-events but for the keyboard peripheral.
> 
> @shyzus Is this issue already created? I was looking for it in that gnome's repo, but I found nothing.

You are right and thank you for commenting on this issue and reminding me I had forgotten to deal with this.

One of the things I ran into when I was working on this was that the gsettings-desktop-schemas repo doesn't implement the settings themselves. Only keeps the schemas that expose the settings so multiple components can interact with them.

I had forgotten to write a post in the gnome discourse to find more info on how to go about implementing this see: https://discourse.gnome.org/t/send-events-setting-for-keyboard/24393 

Now that is there. Once there is more traction on that and I have some development towards I will make a new issue separate from this one to track the future changes.
